# Generated by Django 3.2.9 on 2022-01-21 19:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(default=datetime.date.today)),
                ('sold_currency', models.CharField(max_length=3)),
                ('sold_currency_amount', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MaxValueValidator(0)])),
                ('sold_currency_fee', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MaxValueValidator(0)])),
                ('bought_currency', models.CharField(max_length=3)),
                ('bought_currency_amount', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MaxValueValidator(0)])),
                ('bought_currency_fee', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MaxValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
