# Generated by Django 3.2.9 on 2022-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20220125_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
